"""Generate data/pokemon/special_split.asm from a pokecrystal checkout.

Generation 1 has a single Special stat that serves as both the special attack
and the special defence. Splitting it for real needs about 68 bytes of WRAM0
that this game does not have, so instead the two roles are derived at damage
time from a per-species factor: the stored Special is scaled by the factor for
the role being used. The factors come from each species' genuine Generation 2
Special Attack and Special Defence, normalised so that a species whose two
Generation 2 values are equal is left exactly as it is today.

The factors are not written into the output. The output carries the Generation 2
numbers themselves so the data can be checked against any Pokedex, and the
special_split macro in macros/data.asm turns them into factors at assembly time.

Usage:
    python tools/gen_special_split.py /path/to/pokecrystal
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
OUT = HERE / "data/pokemon/special_split.asm"

# Species with no base stats of their own. Their slots have to be filled so the
# table stays aligned with the species index, but the numbers never get used.
MISSINGNO = "MISSINGNO"

# Species indexes that exist but are not really Pokemon: the two fossils and the
# Marowak ghost, all of which borrow another species' data when they appear.
NOT_A_SPECIES = {"FOSSIL_KABUTOPS", "FOSSIL_AERODACTYL", "MON_GHOST"}

STATS_RE = re.compile(
    r"^\s*db\s+(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\s*$", re.M
)


def internal_order():
    """Species names in index order, straight from the constants file."""
    text = (HERE / "constants/pokemon_constants.asm").read_text()
    names = []
    for line in text.splitlines():
        m = re.match(r"\s*const\s+([A-Z0-9_]+)\s*;\s*\$([0-9A-F]{2})", line)
        if not m:
            continue
        name, index = m.group(1), int(m.group(2), 16)
        if index == 0:
            continue
        while len(names) < index - 1:
            names.append(MISSINGNO)
        names.append(name)
    return names


def gen2_special(crystal):
    """Map each species name to its Generation 2 (Sp.Atk, Sp.Def)."""
    out = {}
    for path in (Path(crystal) / "data/pokemon/base_stats").glob("*.asm"):
        m = STATS_RE.search(path.read_text())
        if not m:
            continue
        out[path.stem.upper()] = (int(m.group(5)), int(m.group(6)))
    return out


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    stats = gen2_special(sys.argv[1])

    # pokered and pokecrystal spell a handful of file names differently.
    aliases = {
        "FARFETCHD": "FARFETCH_D",
        "MR_MIME": "MR__MIME",
    }

    lines = [
        "; Each species' Generation 2 Special Attack and Special Defence.",
        ";",
        "; Generation 1 stores one Special stat for both roles. These numbers let",
        "; the damage code scale that one stat per role, so Alakazam hits hard and",
        "; folds to special attacks while Snorlax does the opposite. The macro turns",
        "; each pair into a factor in sixteenths, normalised so that a species whose",
        "; two values are equal comes out exactly as it is today.",
        ";",
        "; Generated by tools/gen_special_split.py; do not edit by hand.",
        "",
        "SpecialSplitFactors:",
    ]
    missing = []
    for index, name in enumerate(internal_order(), start=1):
        pair = stats.get(aliases.get(name, name))
        if name in NOT_A_SPECIES:
            pair = None
        if name == MISSINGNO or pair is None:
            if name not in NOT_A_SPECIES and name != MISSINGNO:
                missing.append(name)
            lines.append(f"\tspecial_split   1,   1 ; ${index:02x} unused")
            continue
        sat, sdf = pair
        lines.append(f"\tspecial_split {sat:>3}, {sdf:>3} ; ${index:02x} {name}")
    lines.append("")

    if missing:
        print(f"no Generation 2 stats found for: {', '.join(missing)}")
        return 1

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines) - 12} species slots)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
